name: CI
run-name: Build and test
on: [push]
jobs:
  Build:
    runs-on: self-hosted
    steps:
      - name: Install bun
        run: curl -fsSL https://bun.sh/install | bash
      - name: Install dependencies
        run: bun install
      - name: Build
        run: bun build
      - name: Test
        run: bun test
